---
- name: Install Docker
  hosts: ota #ota #prod
  gather_facts: yes
  become: yes
  roles:
    - docker-ansible
    - FDP-ansible-role
  environment:
    https_proxy: http://localhost:3142
    http_proxy: http://localhost:3142
